# Copyright 2020 by the project contributors
# SPDX-License-Identifier: GPL-3.0-only
#
# Author(s): Pavel Benacek <pavel.benacek@gmail.com>

language: python
jobs:
  include:
      - name: "Python 3.8.0 on Xenial Linux"
        python: 3.8           # this works for Linux but is ignored on macOS or Windows
      - name: "Python 3.7.0 on Xenial Linux"
        python: 3.7           # this works for Linux is ingored on macOS or Windows
      - name: "Python 3.7.4 on macOS"
        os: osx
        osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
        language: shell       # 'language: python' is an error on Travis CI macOS

script:
    - bash -x -c "./run-tests.sh"

notifications:
  email: false

